<a href="https://colab.research.google.com/github/Rudra-rudie/RNN-01/blob/main/RNN01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

df = pd.read_csv('/content/100_Unique_QA_Dataset.csv')

df.head()

                                          question      answer
0                   What is the capital of France?       Paris
1                  What is the capital of Germany?      Berlin
2               Who wrote 'To Kill a Mockingbird'?  Harper-Lee
3  What is the largest planet in our solar system?     Jupiter
4   What is the boiling point of water in Celsius?         100

In [ ]:
#tokenize
def tokenize(text):
  text = text.lower()
  text = text.replace('?', ' ')
  text = text.replace("'", "")
  return text.split()

In [ ]:
tokenize('What is the boiling point of water in Celsius?')

['what', 'is', 'the', 'boiling', 'point', 'of', 'water', 'in', 'celsius']

In [ ]:

#vocab
vocab = {'<UNK>':0}

In [ ]:
def build_vocab(row):
  print(row['question'],row['answer'])
  tokenized_question = tokenize(row['question'])
  tokenized_answer = tokenize(row['answer'])
  merged_tokens = tokenized_question + tokenized_answer

  for token in merged_tokens:
    if token not in vocab:
      vocab[token] = len(vocab)

 # print (tokenized_question, tokenized_answer)

In [ ]:
df.apply(build_vocab, axis=1)

What is the capital of France? Paris
What is the capital of Germany? Berlin
Who wrote 'To Kill a Mockingbird'? Harper-Lee
What is the largest planet in our solar system? Jupiter
What is the boiling point of water in Celsius? 100
Who painted the Mona Lisa? Leonardo-da-Vinci
What is the square root of 64? 8
What is the chemical symbol for gold? Au
Which year did World War II end? 1945
What is the longest river in the world? Nile
What is the capital of Japan? Tokyo
Who developed the theory of relativity? Albert-Einstein
What is the freezing point of water in Fahrenheit? 32
Which planet is known as the Red Planet? Mars
Who is the author of '1984'? George-Orwell
What is the currency of the United Kingdom? Pound
What is the capital of India? Delhi
Who discovered gravity? Newton
How many continents are there on Earth? 7
Which gas do plants use for photosynthesis? CO2
What is the smallest prime number? 2
Who invented the telephone? Alexander-Graham-Bell
What is the capital of Australia? Canberra
Which ocean is the largest? Pacific-Ocean
What is the speed of light in vacuum? 299,792,458m/s
Which language is spoken in Brazil? Portuguese
Who discovered penicillin? Alexander-Fleming
What is the capital of Canada? Ottawa
What is the largest mammal on Earth? Whale
Which element has the atomic number 1? Hydrogen
What is the tallest mountain in the world? Everest
Which city is known as the Big Apple? NewYork
How many planets are in the Solar System? 8
Who painted 'Starry Night'? vangogh
What is the chemical formula of water? H2O
What is the capital of Italy? Rome
Which country is famous for sushi? Japan
Who was the first person to step on the Moon? Armstrong
What is the main ingredient in guacamole? Avocado
How many sides does a hexagon have? 6
What is the currency of China? Yuan
Who wrote 'Pride and Prejudice'? Jane-Austen
What is the chemical symbol for iron? Fe
What is the hardest natural substance on Earth? Diamond
Which continent is the largest by area? Asia
Who was the first President of the United States? George-Washington
Which bird is known for its ability to mimic sounds? Parrot
What is the longest-running animated TV show? Simpsons
What is the smallest country in the world? VaticanCity
Which planet has the most moons? Saturn
Who wrote 'Romeo and Juliet'? Shakespeare
What is the main gas in Earth's atmosphere? Nitrogen
How many bones are in the adult human body? 206
Which metal is a liquid at room temperature? Mercury
What is the capital of Russia? Moscow
Who discovered electricity? Benjamin-Franklin
Which is the second-largest country by land area? Canada
What is the color of a ripe banana? Yellow
Which month has 28 days in a common year? February
What is the study of living organisms called? Biology
Which country is home to the Great Wall? China
What do bees collect from flowers? Nectar
What is the opposite of 'day'? Night
What is the capital of South Korea? Seoul
Who invented the light bulb? Edison
Which gas do humans breathe in for survival? Oxygen
What is the square root of 144? 12
Which country has the pyramids of Giza? Egypt
Which sea creature has eight arms? Octopus
Which holiday is celebrated on December 25? Christmas
What is the currency of Japan? Yen
How many legs does a spider have? 8
Which sport uses a net, ball, and hoop? Basketball
Which country is famous for its kangaroos? Australia
Who was the first female Prime Minister of the UK? MargaretThatcher
Which is the fastest land animal? Cheetah
What is the first element on the periodic table? Hydrogen
What is the capital of Spain? Madrid
Which planet is the closest to the Sun? Mercury
Who is known as the father of computers? CharlesBabbage
What is the capital of Mexico? MexicoCity
How many colors are in a rainbow? 7
Which musical instrument has black and white keys? Piano
Who discovered the Americas in 1492? ChristopherColumbus
Which Disney character has a long nose and grows it when lying? Pinocchio
Who directed the movie 'Titanic'? JamesCameron
Which superhero is also known as the Dark Knight? Batman
What is the capital of Brazil? Brasilia
Which fruit is known as the king of fruits? Mango
Which country is known for the Eiffel Tower? France

0     None
1     None
2     None
3     None
4     None
      ...
85    None
86    None
87    None
88    None
89    None
Length: 90, dtype: object

In [ ]:
vocab

{'<UNK>': 0,
 'what': 1,
 'is': 2,
 'the': 3,
 'capital': 4,
 'of': 5,
 'france': 6,
 'paris': 7,
 'germany': 8,
 'berlin': 9,
 'who': 10,
 'wrote': 11,
 'to': 12,
 'kill': 13,
 'a': 14,
 'mockingbird': 15,
 'harper-lee': 16,
 'largest': 17,
 'planet': 18,
 'in': 19,
 'our': 20,
 'solar': 21,
 'system': 22,
 'jupiter': 23,
 'boiling': 24,
 'point': 25,
 'water': 26,
 'celsius': 27,
 '100': 28,
 'painted': 29,
 'mona': 30,
 'lisa': 31,
 'leonardo-da-vinci': 32,
 'square': 33,
 'root': 34,
 '64': 35,
 '8': 36,
 'chemical': 37,
 'symbol': 38,
 'for': 39,
 'gold': 40,
 'au': 41,
 'which': 42,
 'year': 43,
 'did': 44,
 'world': 45,
 'war': 46,
 'ii': 47,
 'end': 48,
 '1945': 49,
 'longest': 50,
 'river': 51,
 'nile': 52,
 'japan': 53,
 'tokyo': 54,
 'developed': 55,
 'theory': 56,
 'relativity': 57,
 'albert-einstein': 58,
 'freezing': 59,
 'fahrenheit': 60,
 '32': 61,
 'known': 62,
 'as': 63,
 'red': 64,
 'mars': 65,
 'author': 66,
 '1984': 67,
 'george-orwell': 68,
 'currency': 69,
 'united': 70,
 'kingdom': 71,
 'pound': 72,
 'india': 73,
 'delhi': 74,
 'discovered': 75,
 'gravity': 76,
 'newton': 77,
 'how': 78,
 'many': 79,
 'continents': 80,
 'are': 81,
 'there': 82,
 'on': 83,
 'earth': 84,
 '7': 85,
 'gas': 86,
 'do': 87,
 'plants': 88,
 'use': 89,
 'photosynthesis': 90,
 'co2': 91,
 'smallest': 92,
 'prime': 93,
 'number': 94,
 '2': 95,
 'invented': 96,
 'telephone': 97,
 'alexander-graham-bell': 98,
 'australia': 99,
 'canberra': 100,
 'ocean': 101,
 'pacific-ocean': 102,
 'speed': 103,
 'light': 104,
 'vacuum': 105,
 '299,792,458m/s': 106,
 'language': 107,
 'spoken': 108,
 'brazil': 109,
 'portuguese': 110,
 'penicillin': 111,
 'alexander-fleming': 112,
 'canada': 113,
 'ottawa': 114,
 'mammal': 115,
 'whale': 116,
 'element': 117,
 'has': 118,
 'atomic': 119,
 '1': 120,
 'hydrogen': 121,
 'tallest': 122,
 'mountain': 123,
 'everest': 124,
 'city': 125,
 'big': 126,
 'apple': 127,
 'newyork': 128,
 'planets': 129,
 'starry': 130,
 'night': 131,
 'vangogh': 132,
 'formula': 133,
 'h2o': 134,
 'italy': 135,
 'rome': 136,
 'country': 137,
 'famous': 138,
 'sushi': 139,
 'was': 140,
 'first': 141,
 'person': 142,
 'step': 143,
 'moon': 144,
 'armstrong': 145,
 'main': 146,
 'ingredient': 147,
 'guacamole': 148,
 'avocado': 149,
 'sides': 150,
 'does': 151,
 'hexagon': 152,
 'have': 153,
 '6': 154,
 'china': 155,
 'yuan': 156,
 'pride': 157,
 'and': 158,
 'prejudice': 159,
 'jane-austen': 160,
 'iron': 161,
 'fe': 162,
 'hardest': 163,
 'natural': 164,
 'substance': 165,
 'diamond': 166,
 'continent': 167,
 'by': 168,
 'area': 169,
 'asia': 170,
 'president': 171,
 'states': 172,
 'george-washington': 173,
 'bird': 174,
 'its': 175,
 'ability': 176,
 'mimic': 177,
 'sounds': 178,
 'parrot': 179,
 'longest-running': 180,
 'animated': 181,
 'tv': 182,
 'show': 183,
 'simpsons': 184,
 'vaticancity': 185,
 'most': 186,
 'moons': 187,
 'saturn': 188,
 'romeo': 189,
 'juliet': 190,
 'shakespeare': 191,
 'earths': 192,
 'atmosphere': 193,
 'nitrogen': 194,
 'bones': 195,
 'adult': 196,
 'human': 197,
 'body': 198,
 '206': 199,
 'metal': 200,
 'liquid': 201,
 'at': 202,
 'room': 203,
 'temperature': 204,
 'mercury': 205,
 'russia': 206,
 'moscow': 207,
 'electricity': 208,
 'benjamin-franklin': 209,
 'second-largest': 210,
 'land': 211,
 'color': 212,
 'ripe': 213,
 'banana': 214,
 'yellow': 215,
 'month': 216,
 '28': 217,
 'days': 218,
 'common': 219,
 'february': 220,
 'study': 221,
 'living': 222,
 'organisms': 223,
 'called': 224,
 'biology': 225,
 'home': 226,
 'great': 227,
 'wall': 228,
 'bees': 229,
 'collect': 230,
 'from': 231,
 'flowers': 232,
 'nectar': 233,
 'opposite': 234,
 'day': 235,
 'south': 236,
 'korea': 237,
 'seoul': 238,
 'bulb': 239,
 'edison': 240,
 'humans': 241,
 'breathe': 242,
 'survival': 243,
 'oxygen': 244,
 '144': 245,
 '12': 246,
 'pyramids': 247,
 'giza': 248,
 'egypt': 249,
 'sea': 250,
 'creature': 251,
 'eight': 252,
 'arms': 253,
 'octopus': 254,
 'holiday': 255,
 'celebrated': 256,
 'december': 257,
 '25': 258,
 'christmas': 259,
 'yen': 260,
 'legs': 261,
 'spider': 262,
 'sport': 263,
 'uses': 264,
 'net,': 265,
 'ball,': 266,
 'hoop': 267,
 'basketball': 268,
 'kangaroos': 269,
 'female': 270,
 'minister': 271,
 'uk': 272,
 'margaretthatcher': 273,
 'fastest': 274,
 'animal': 275,
 'cheetah': 276,
 'periodic': 277,
 'table': 278,
 'spain': 279,
 'madrid': 280,
 'closest': 281,
 'sun': 282,
 'father': 283,
 'computers': 284,
 'charlesbabbage': 285,
 'mexico': 286,
 'mexicocity': 287,
 'colors': 288,
 'rainbow': 289,
 'musical': 290,
 'instrument': 291,
 'black': 292,
 'white': 293,
 'keys': 294,
 'piano': 295,
 'americas': 296,
 '1492': 297,
 'christophercolumbus': 298,
 'disney': 299,
 'character': 300,
 'long': 301,
 'nose': 302,
 'grows': 303,
 'it': 304,
 'when': 305,
 'lying': 306,
 'pinocchio': 307,
 'directed': 308,
 'movie': 309,
 'titanic': 310,
 'jamescameron': 311,
 'superhero': 312,
 'also': 313,
 'dark': 314,
 'knight': 315,
 'batman': 316,
 'brasilia': 317,
 'fruit': 318,
 'king': 319,
 'fruits': 320,
 'mango': 321,
 'eiffel': 322,
 'tower': 323}

In [ ]:
len(vocab)

324

In [ ]:
#conversion
def text_to_indices(text, vocab):
  indexed_text=[]
  for token in tokenize(text):
    if token in vocab:
      indexed_text.append(vocab[token])
    else:
      indexed_text.append(vocab['<UNK>'])

  return indexed_text

In [ ]:
import torch
from torch.utils.data import Dataset, DataLoader

In [ ]:
class QADataset(Dataset):
    def __init__(self, df, vocab):
        self.df = df
        self.vocab = vocab
    def __len__(self):
        return self.df.shape[0]
    def __getitem__(self,index):
        # self.df.iloc[index] # This line was not doing anything, can be removed or implicitly handled by next lines
        numericalized_question = text_to_indices(self.df.iloc[index]['question'], self.vocab)
        numericalized_answer = text_to_indices(self.df.iloc[index]['answer'], self.vocab)

        return torch.tensor(numericalized_question), torch.tensor(numericalized_answer)

In [ ]:
dataset = QADataset(df,vocab)

In [ ]:
dataset = QADataset(df,vocab)
dataset[10]

(tensor([ 1,  2,  3,  4,  5, 53]), tensor([54]))

In [ ]:
dataloader= DataLoader(dataset, batch_size=1, shuffle=True)

In [ ]:
for question, answer in dataloader:
  print(question, answer)

tensor([[10,  2,  3, 66,  5, 67]]) tensor([[68]])
tensor([[ 10,  11, 189, 158, 190]]) tensor([[191]])
tensor([[ 10,  75, 111]]) tensor([[112]])
tensor([[  1,   2,   3,   4,   5, 279]]) tensor([[280]])
tensor([[  1,   2,   3,   4,   5, 286]]) tensor([[287]])
tensor([[  1,   2,   3, 103,   5, 104,  19, 105]]) tensor([[106]])
tensor([[  1,   2,   3, 180, 181, 182, 183]]) tensor([[184]])
tensor([[ 1,  2,  3,  4,  5, 53]]) tensor([[54]])
tensor([[10, 75, 76]]) tensor([[77]])
tensor([[ 10,  96,   3, 104, 239]]) tensor([[240]])
tensor([[  1,   2,   3, 146,  86,  19, 192, 193]]) tensor([[194]])
tensor([[  1,   2,   3,  17, 115,  83,  84]]) tensor([[116]])
tensor([[1, 2, 3, 4, 5, 6]]) tensor([[7]])
tensor([[  1,   2,   3, 122, 123,  19,   3,  45]]) tensor([[124]])
tensor([[ 1,  2,  3, 92, 93, 94]]) tensor([[95]])
tensor([[ 42, 174,   2,  62,  39, 175, 176,  12, 177, 178]]) tensor([[179]])
tensor([[ 42, 200,   2,  14, 201, 202, 203, 204]]) tensor([[205]])
tensor([[ 10,  29, 130, 131]]) tensor([[132]])
tensor([[42, 86, 87, 88, 89, 39, 90]]) tensor([[91]])
tensor([[ 42,   2,   3, 274, 211, 275]]) tensor([[276]])
tensor([[10, 11, 12, 13, 14, 15]]) tensor([[16]])
tensor([[ 1,  2,  3, 69,  5,  3, 70, 71]]) tensor([[72]])
tensor([[ 1,  2,  3,  4,  5, 99]]) tensor([[100]])
tensor([[ 42, 101,   2,   3,  17]]) tensor([[102]])
tensor([[ 42, 312,   2, 313,  62,  63,   3, 314, 315]]) tensor([[316]])
tensor([[ 78,  79, 129,  81,  19,   3,  21,  22]]) tensor([[36]])
tensor([[  1,   2,   3,  92, 137,  19,   3,  45]]) tensor([[185]])
tensor([[10, 96,  3, 97]]) tensor([[98]])
tensor([[ 1,  2,  3, 59, 25,  5, 26, 19, 60]]) tensor([[61]])
tensor([[ 1,  2,  3, 69,  5, 53]]) tensor([[260]])
tensor([[10, 29,  3, 30, 31]]) tensor([[32]])
tensor([[ 10,  11, 157, 158, 159]]) tensor([[160]])
tensor([[ 42,  18,   2,   3, 281,  12,   3, 282]]) tensor([[205]])
tensor([[ 1,  2,  3, 37, 38, 39, 40]]) tensor([[41]])
tensor([[ 42, 137,   2, 138,  39, 175, 269]]) tensor([[99]])
tensor([[ 42, 107,   2, 108,  19, 109]]) tensor([[110]])
tensor([[ 42, 216, 118, 217, 218,  19,  14, 219,  43]]) tensor([[220]])
tensor([[ 42,   2,   3, 210, 137, 168, 211, 169]]) tensor([[113]])
tensor([[  1,   2,   3,  33,  34,   5, 245]]) tensor([[246]])
tensor([[ 42, 255,   2, 256,  83, 257, 258]]) tensor([[259]])
tensor([[ 10, 140,   3, 141, 142,  12, 143,  83,   3, 144]]) tensor([[145]])
tensor([[ 42, 125,   2,  62,  63,   3, 126, 127]]) tensor([[128]])
tensor([[  1,   2,   3,  37, 133,   5,  26]]) tensor([[134]])
tensor([[  1,  87, 229, 230, 231, 232]]) tensor([[233]])
tensor([[  1,   2,   3,   4,   5, 113]]) tensor([[114]])
tensor([[ 42, 318,   2,  62,  63,   3, 319,   5, 320]]) tensor([[321]])
tensor([[78, 79, 80, 81, 82, 83, 84]]) tensor([[85]])
tensor([[ 1,  2,  3,  4,  5, 73]]) tensor([[74]])
tensor([[  1,   2,   3,  69,   5, 155]]) tensor([[156]])
tensor([[ 10, 308,   3, 309, 310]]) tensor([[311]])
tensor([[ 42, 137,   2, 138,  39, 139]]) tensor([[53]])
tensor([[ 42,  86,  87, 241, 242,  19,  39, 243]]) tensor([[244]])
tensor([[ 78,  79, 288,  81,  19,  14, 289]]) tensor([[85]])
tensor([[ 42,  18, 118,   3, 186, 187]]) tensor([[188]])
tensor([[  1,   2,   3, 146, 147,  19, 148]]) tensor([[149]])
tensor([[ 78,  79, 261, 151,  14, 262, 153]]) tensor([[36]])
tensor([[ 42, 137, 118,   3, 247,   5, 248]]) tensor([[249]])
tensor([[ 10, 140,   3, 141, 171,   5,   3,  70, 172]]) tensor([[173]])
tensor([[ 42, 299, 300, 118,  14, 301, 302, 158, 303, 304, 305, 306]]) tensor([[307]])
tensor([[42, 43, 44, 45, 46, 47, 48]]) tensor([[49]])
tensor([[  1,   2,   3, 163, 164, 165,  83,  84]]) tensor([[166]])
tensor([[1, 2, 3, 4, 5, 8]]) tensor([[9]])
tensor([[ 10,   2,  62,  63,   3, 283,   5, 284]]) tensor([[285]])
tensor([[ 10,  75,   3, 296,  19, 297]]) tensor([[298]])
tensor([[ 78,  79, 195,  81,  19,   3, 196, 197, 198]]) tensor([[199]])
tensor([[ 10, 140,   3, 141, 270,  93, 271,   5,   3, 272]]) tensor([[273]])
tensor([[ 42, 250, 251, 118, 252, 253]]) tensor([[254]])
tensor([[ 78,  79, 150, 151,  14, 152, 153]]) tensor([[154]])
tensor([[ 1,  2,  3, 33, 34,  5, 35]]) tensor([[36]])
tensor([[  1,   2,   3, 221,   5, 222, 223, 224]]) tensor([[225]])
tensor([[  1,   2,   3, 212,   5,  14, 213, 214]]) tensor([[215]])
tensor([[  1,   2,   3,   4,   5, 135]]) tensor([[136]])
tensor([[  1,   2,   3, 234,   5, 235]]) tensor([[131]])
tensor([[  1,   2,   3,   4,   5, 236, 237]]) tensor([[238]])
tensor([[  1,   2,   3,   4,   5, 109]]) tensor([[317]])
tensor([[ 42, 137,   2, 226,  12,   3, 227, 228]]) tensor([[155]])
tensor([[ 1,  2,  3, 24, 25,  5, 26, 19, 27]]) tensor([[28]])
tensor([[ 42, 263, 264,  14, 265, 266, 158, 267]]) tensor([[268]])
tensor([[42, 18,  2, 62, 63,  3, 64, 18]]) tensor([[65]])
tensor([[ 42, 167,   2,   3,  17, 168, 169]]) tensor([[170]])
tensor([[ 10,  75, 208]]) tensor([[209]])
tensor([[ 1,  2,  3, 17, 18, 19, 20, 21, 22]]) tensor([[23]])
tensor([[ 42, 117, 118,   3, 119,  94, 120]]) tensor([[121]])
tensor([[  1,   2,   3, 141, 117,  83,   3, 277, 278]]) tensor([[121]])
tensor([[  1,   2,   3,   4,   5, 206]]) tensor([[207]])
tensor([[ 42, 137,   2,  62,  39,   3, 322, 323]]) tensor([[6]])
tensor([[ 1,  2,  3, 50, 51, 19,  3, 45]]) tensor([[52]])
tensor([[ 42, 290, 291, 118, 292, 158, 293, 294]]) tensor([[295]])
tensor([[10, 55,  3, 56,  5, 57]]) tensor([[58]])
tensor([[  1,   2,   3,  37,  38,  39, 161]]) tensor([[162]])

In [ ]:
 import torch.nn as nn

In [ ]:
class SimpleNN(nn.Module):
  def __init__(self, vocab_size):
    super().__init__()
    self.embedding = nn.Embedding(vocab_size, embedding_dim=50)
    self.rnn = nn.RNN(50, 64)
    self.fc = nn.Linear(64, vocab_size)
    self.sigmoid = nn.Sigmoid()

  def forward(self, question):
    embedded = self.embedding(question)
    output, hidden = self.rnn(embedded)
    output = self.fc(output)
    # The forward pass logic would go here, taking an input 'x'
    return output

In [ ]:
a = x(dataset[0][0].long())

In [ ]:
a = x(dataset[0][0])

In [ ]:
y = nn.RNN(50,64)

In [ ]:
print(f"Shape of 'a' before RNN: {a.shape}")
print(f"Last dimension of 'a' before RNN: {a.size(-1)}")
y(a)

Shape of 'a' before RNN: torch.Size([6, 50])
Last dimension of 'a' before RNN: 50

(tensor([[ 5.5401e-01,  1.9081e-01,  8.5116e-03, -3.5920e-01,  2.4056e-01,
           5.9345e-01, -3.6784e-01, -2.2223e-01, -2.1636e-01,  7.5029e-01,
          -3.1147e-01,  1.2056e-01,  2.5609e-01,  2.5749e-01, -2.5278e-01,
          -1.0423e-01,  8.0931e-01,  2.7781e-01, -7.8059e-01, -8.8724e-02,
          -1.4242e-01,  5.5975e-01,  9.1053e-02, -6.5654e-01,  6.3162e-01,
           7.1690e-01,  4.1784e-01, -7.9628e-02, -7.0323e-01, -3.7468e-01,
           3.0424e-01, -5.7182e-02, -7.5154e-01,  1.3576e-01,  4.4423e-01,
           7.0530e-01,  7.1435e-04,  2.8914e-01,  4.2635e-01,  1.8026e-01,
          -9.5965e-02, -5.1166e-01, -1.7773e-01, -2.4615e-01, -1.9695e-01,
           3.7077e-01,  6.5249e-01,  2.6905e-01, -8.3913e-02,  1.9560e-01,
          -3.2070e-02,  4.2597e-01,  3.4668e-01,  8.6777e-02, -9.1486e-02,
          -4.2942e-02, -8.3585e-01, -5.9397e-01, -6.6350e-01, -2.3961e-01,
          -6.1699e-01,  3.6343e-01,  8.6641e-01, -6.3722e-01],
         [ 1.1916e-01, -5.9076e-01, -1.2900e-01, -1.1616e-01, -5.5782e-01,
          -4.3628e-01,  4.8781e-01,  1.8055e-01, -2.4173e-02,  5.1973e-01,
           4.5292e-01,  4.8972e-01,  7.8048e-01,  2.9344e-01, -5.7243e-02,
          -3.4883e-01, -9.3893e-02, -8.5968e-01,  3.7790e-01, -3.3999e-01,
          -7.0246e-01,  1.3516e-01,  1.3376e-01, -1.7089e-01,  2.1935e-01,
          -3.7219e-01, -9.2295e-02, -1.0301e-01,  3.9321e-01, -1.8085e-02,
           2.5790e-01,  7.3121e-01,  7.2058e-01,  1.5364e-01, -1.3806e-01,
          -4.1927e-01, -6.1626e-01, -1.9162e-01,  2.0608e-01,  1.5725e-01,
           2.2822e-01,  1.5405e-01,  7.5066e-01,  7.6794e-01,  1.0800e-01,
           5.2191e-01, -1.0381e-01,  5.0817e-02,  4.5487e-01,  1.4389e-01,
           3.6821e-01, -3.0147e-01,  5.9830e-01, -4.5007e-01, -5.3071e-01,
          -3.5833e-01,  3.4990e-01, -6.5140e-01,  8.5080e-01,  5.1897e-01,
           5.0447e-01, -1.5747e-01, -2.4306e-01,  4.2304e-01],
         [-4.8384e-01, -3.3818e-01,  5.4384e-02,  7.7408e-01, -5.8362e-01,
           8.2099e-01,  2.5112e-01,  1.4784e-01, -5.9834e-01,  3.2054e-01,
          -5.5226e-01,  7.9720e-01, -2.2604e-01, -2.0353e-01, -4.3746e-01,
          -3.3166e-01,  7.3346e-01, -1.5895e-01,  1.6771e-02, -8.9021e-01,
          -7.1876e-02,  6.4186e-01, -6.8890e-02, -1.7524e-01,  4.3869e-01,
           4.8035e-01,  5.7224e-01, -1.3964e-02, -4.8310e-01, -2.2006e-01,
           6.7319e-01,  2.5686e-01,  5.6276e-01, -5.0287e-01, -2.0029e-01,
          -2.0322e-01,  2.2802e-01, -2.9272e-01,  7.4341e-01,  5.5960e-01,
          -4.6573e-01,  9.0392e-01,  3.5685e-01,  4.2366e-02,  4.6419e-01,
           7.6738e-01, -3.8267e-01,  9.7017e-02,  4.3550e-01, -5.9207e-01,
          -1.9873e-01,  3.6149e-01, -6.6294e-01, -3.9650e-01, -5.8481e-01,
          -4.0074e-01, -5.4497e-01, -8.5026e-01, -6.4857e-01, -7.1790e-01,
          -7.4610e-01,  1.3397e-01, -6.3842e-01,  6.2323e-01],
         [ 4.7319e-01,  3.0412e-01, -2.8677e-01, -1.1755e-01,  8.7733e-01,
           3.9947e-01,  5.9321e-01, -4.3129e-01, -5.9532e-02, -6.0064e-01,
           6.9711e-01, -5.3187e-01, -1.9331e-01,  5.2546e-01,  8.9326e-02,
          -2.4038e-01,  3.5236e-01,  5.5974e-01, -6.5253e-01, -2.5275e-01,
          -4.6029e-01,  1.5766e-01,  2.3446e-01, -5.7259e-01,  1.1880e-01,
          -4.4975e-01, -1.8210e-01,  2.1866e-01,  5.2721e-01,  1.2615e-01,
           2.6158e-01,  6.7523e-01, -4.8115e-01,  2.4834e-02, -1.8628e-01,
           4.4641e-01, -1.6244e-01,  6.6358e-02,  6.0561e-02, -6.8964e-01,
           5.9434e-01, -2.4524e-01,  2.9316e-01,  1.8658e-01,  7.7831e-02,
          -5.2396e-01,  3.5562e-01, -8.2206e-01,  2.5517e-01,  2.7797e-01,
           7.3485e-01,  3.1642e-01,  4.2581e-01,  2.0421e-01, -6.7145e-01,
          -5.2483e-01,  8.8962e-02,  9.1819e-01, -9.2882e-01, -3.4019e-01,
          -6.7517e-01, -1.6471e-01,  1.8738e-01, -5.5556e-01],
         [-2.8668e-01,  4.6694e-01, -7.9829e-01, -4.8198e-01,  3.6108e-01,
           2.3905e-01, -3.8592e-01,  7.3817e-01,  3.5980e-01,  4.7340e-01,
           7.7391e-02, -6.0818e-01, -8.8296e-01, -8.0889e-02, -4.7601e-01,
          -2.1095e-01, -6.8668e-01,  4.2994e-01, -6.2851e-02,  1.1702e-01,
          -3.8532e-01, -1.6087e-01, -5.4951e-01, -4.5865e-01,  5.9352e-01,
           6.2155e-01,  4.1810e-02, -1.6281e-03,  5.1808e-02,  5.8248e-01,
           6.9517e-01,  2.5775e-01, -3.8549e-01,  3.2064e-01,  1.5843e-01,
          -1.8417e-01, -3.2468e-01,  3.6854e-01, -5.9146e-01,  3.8898e-01,
           4.1324e-01, -4.7287e-01, -4.6431e-01, -1.0797e-01,  2.4077e-01,
           6.9633e-01,  7.7392e-01,  8.0287e-01, -1.7880e-01,  6.8888e-01,
          -1.9605e-01, -4.1102e-01, -1.7786e-01,  2.8578e-01,  1.4822e-01,
          -8.3104e-01, -4.9572e-01, -3.9485e-01, -1.6031e-01,  6.7422e-01,
          -5.3503e-01,  1.4893e-01, -2.5162e-01,  7.7806e-02],
         [ 1.6816e-01, -5.7606e-01, -6.5634e-01, -1.5989e-01,  8.3986e-01,
           2.9806e-01,  6.9713e-01, -5.2823e-01,  3.9010e-01,  3.3417e-01,
          -1.4677e-01,  3.3954e-01,  7.4682e-01, -5.4041e-01, -5.0909e-01,
           6.8189e-01,  9.5224e-02, -5.4321e-01,  2.3478e-01,  8.9916e-01,
          -5.8353e-01, -6.1312e-01,  6.6431e-01, -1.1991e-02,  3.9430e-01,
          -7.7222e-01, -4.4673e-01, -1.1034e-02,  5.9963e-01, -2.6545e-02,
          -3.3923e-01,  1.0168e-01,  3.6542e-01,  6.9680e-01, -5.7745e-01,
           2.6047e-01,  8.8678e-01, -7.2684e-01,  2.9774e-01, -2.2862e-01,
          -2.6925e-01, -6.0415e-01, -4.8735e-01,  6.8570e-01,  1.2674e-01,
          -3.7454e-01,  3.8836e-01, -1.4712e-01, -2.5363e-01,  2.4132e-01,
          -3.1939e-01,  6.6635e-01,  8.1498e-01, -1.9068e-01, -4.7592e-01,
           1.4402e-01,  6.9687e-01,  6.9328e-01, -5.6145e-01,  6.1426e-01,
          -1.4520e-01,  3.2515e-01,  2.2321e-01, -6.8992e-01]],
        grad_fn=<SqueezeBackward1>),
 tensor([[ 0.1682, -0.5761, -0.6563, -0.1599,  0.8399,  0.2981,  0.6971, -0.5282,
           0.3901,  0.3342, -0.1468,  0.3395,  0.7468, -0.5404, -0.5091,  0.6819,
           0.0952, -0.5432,  0.2348,  0.8992, -0.5835, -0.6131,  0.6643, -0.0120,
           0.3943, -0.7722, -0.4467, -0.0110,  0.5996, -0.0265, -0.3392,  0.1017,
           0.3654,  0.6968, -0.5774,  0.2605,  0.8868, -0.7268,  0.2977, -0.2286,
          -0.2692, -0.6042, -0.4874,  0.6857,  0.1267, -0.3745,  0.3884, -0.1471,
          -0.2536,  0.2413, -0.3194,  0.6663,  0.8150, -0.1907, -0.4759,  0.1440,
           0.6969,  0.6933, -0.5615,  0.6143, -0.1452,  0.3252,  0.2232, -0.6899]],
        grad_fn=<SqueezeBackward1>))

In [ ]:
y(a)

(tensor([[ 5.5401e-01,  1.9081e-01,  8.5116e-03, -3.5920e-01,  2.4056e-01,
           5.9345e-01, -3.6784e-01, -2.2223e-01, -2.1636e-01,  7.5029e-01,
          -3.1147e-01,  1.2056e-01,  2.5609e-01,  2.5749e-01, -2.5278e-01,
          -1.0423e-01,  8.0931e-01,  2.7781e-01, -7.8059e-01, -8.8724e-02,
          -1.4242e-01,  5.5975e-01,  9.1053e-02, -6.5654e-01,  6.3162e-01,
           7.1690e-01,  4.1784e-01, -7.9628e-02, -7.0323e-01, -3.7468e-01,
           3.0424e-01, -5.7182e-02, -7.5154e-01,  1.3576e-01,  4.4423e-01,
           7.0530e-01,  7.1435e-04,  2.8914e-01,  4.2635e-01,  1.8026e-01,
          -9.5965e-02, -5.1166e-01, -1.7773e-01, -2.4615e-01, -1.9695e-01,
           3.7077e-01,  6.5249e-01,  2.6905e-01, -8.3913e-02,  1.9560e-01,
          -3.2070e-02,  4.2597e-01,  3.4668e-01,  8.6777e-02, -9.1486e-02,
          -4.2942e-02, -8.3585e-01, -5.9397e-01, -6.6350e-01, -2.3961e-01,
          -6.1699e-01,  3.6343e-01,  8.6641e-01, -6.3722e-01],
         [ 1.1916e-01, -5.9076e-01, -1.2900e-01, -1.1616e-01, -5.5782e-01,
          -4.3628e-01,  4.8781e-01,  1.8055e-01, -2.4173e-02,  5.1973e-01,
           4.5292e-01,  4.8972e-01,  7.8048e-01,  2.9344e-01, -5.7243e-02,
          -3.4883e-01, -9.3893e-02, -8.5968e-01,  3.7790e-01, -3.3999e-01,
          -7.0246e-01,  1.3516e-01,  1.3376e-01, -1.7089e-01,  2.1935e-01,
          -3.7219e-01, -9.2295e-02, -1.0301e-01,  3.9321e-01, -1.8085e-02,
           2.5790e-01,  7.3121e-01,  7.2058e-01,  1.5364e-01, -1.3806e-01,
          -4.1927e-01, -6.1626e-01, -1.9162e-01,  2.0608e-01,  1.5725e-01,
           2.2822e-01,  1.5405e-01,  7.5066e-01,  7.6794e-01,  1.0800e-01,
           5.2191e-01, -1.0381e-01,  5.0817e-02,  4.5487e-01,  1.4389e-01,
           3.6821e-01, -3.0147e-01,  5.9830e-01, -4.5007e-01, -5.3071e-01,
          -3.5833e-01,  3.4990e-01, -6.5140e-01,  8.5080e-01,  5.1897e-01,
           5.0447e-01, -1.5747e-01, -2.4306e-01,  4.2304e-01],
         [-4.8384e-01, -3.3818e-01,  5.4384e-02,  7.7408e-01, -5.8362e-01,
           8.2099e-01,  2.5112e-01,  1.4784e-01, -5.9834e-01,  3.2054e-01,
          -5.5226e-01,  7.9720e-01, -2.2604e-01, -2.0353e-01, -4.3746e-01,
          -3.3166e-01,  7.3346e-01, -1.5895e-01,  1.6771e-02, -8.9021e-01,
          -7.1876e-02,  6.4186e-01, -6.8890e-02, -1.7524e-01,  4.3869e-01,
           4.8035e-01,  5.7224e-01, -1.3964e-02, -4.8310e-01, -2.2006e-01,
           6.7319e-01,  2.5686e-01,  5.6276e-01, -5.0287e-01, -2.0029e-01,
          -2.0322e-01,  2.2802e-01, -2.9272e-01,  7.4341e-01,  5.5960e-01,
          -4.6573e-01,  9.0392e-01,  3.5685e-01,  4.2366e-02,  4.6419e-01,
           7.6738e-01, -3.8267e-01,  9.7017e-02,  4.3550e-01, -5.9207e-01,
          -1.9873e-01,  3.6149e-01, -6.6294e-01, -3.9650e-01, -5.8481e-01,
          -4.0074e-01, -5.4497e-01, -8.5026e-01, -6.4857e-01, -7.1790e-01,
          -7.4610e-01,  1.3397e-01, -6.3842e-01,  6.2323e-01],
         [ 4.7319e-01,  3.0412e-01, -2.8677e-01, -1.1755e-01,  8.7733e-01,
           3.9947e-01,  5.9321e-01, -4.3129e-01, -5.9532e-02, -6.0064e-01,
           6.9711e-01, -5.3187e-01, -1.9331e-01,  5.2546e-01,  8.9326e-02,
          -2.4038e-01,  3.5236e-01,  5.5974e-01, -6.5253e-01, -2.5275e-01,
          -4.6029e-01,  1.5766e-01,  2.3446e-01, -5.7259e-01,  1.1880e-01,
          -4.4975e-01, -1.8210e-01,  2.1866e-01,  5.2721e-01,  1.2615e-01,
           2.6158e-01,  6.7523e-01, -4.8115e-01,  2.4834e-02, -1.8628e-01,
           4.4641e-01, -1.6244e-01,  6.6358e-02,  6.0561e-02, -6.8964e-01,
           5.9434e-01, -2.4524e-01,  2.9316e-01,  1.8658e-01,  7.7831e-02,
          -5.2396e-01,  3.5562e-01, -8.2206e-01,  2.5517e-01,  2.7797e-01,
           7.3485e-01,  3.1642e-01,  4.2581e-01,  2.0421e-01, -6.7145e-01,
          -5.2483e-01,  8.8962e-02,  9.1819e-01, -9.2882e-01, -3.4019e-01,
          -6.7517e-01, -1.6471e-01,  1.8738e-01, -5.5556e-01],
         [-2.8668e-01,  4.6694e-01, -7.9829e-01, -4.8198e-01,  3.6108e-01,
           2.3905e-01, -3.8592e-01,  7.3817e-01,  3.5980e-01,  4.7340e-01,
           7.7391e-02, -6.0818e-01, -8.8296e-01, -8.0889e-02, -4.7601e-01,
          -2.1095e-01, -6.8668e-01,  4.2994e-01, -6.2851e-02,  1.1702e-01,
          -3.8532e-01, -1.6087e-01, -5.4951e-01, -4.5865e-01,  5.9352e-01,
           6.2155e-01,  4.1810e-02, -1.6281e-03,  5.1808e-02,  5.8248e-01,
           6.9517e-01,  2.5775e-01, -3.8549e-01,  3.2064e-01,  1.5843e-01,
          -1.8417e-01, -3.2468e-01,  3.6854e-01, -5.9146e-01,  3.8898e-01,
           4.1324e-01, -4.7287e-01, -4.6431e-01, -1.0797e-01,  2.4077e-01,
           6.9633e-01,  7.7392e-01,  8.0287e-01, -1.7880e-01,  6.8888e-01,
          -1.9605e-01, -4.1102e-01, -1.7786e-01,  2.8578e-01,  1.4822e-01,
          -8.3104e-01, -4.9572e-01, -3.9485e-01, -1.6031e-01,  6.7422e-01,
          -5.3503e-01,  1.4893e-01, -2.5162e-01,  7.7806e-02],
         [ 1.6816e-01, -5.7606e-01, -6.5634e-01, -1.5989e-01,  8.3986e-01,
           2.9806e-01,  6.9713e-01, -5.2823e-01,  3.9010e-01,  3.3417e-01,
          -1.4677e-01,  3.3954e-01,  7.4682e-01, -5.4041e-01, -5.0909e-01,
           6.8189e-01,  9.5224e-02, -5.4321e-01,  2.3478e-01,  8.9916e-01,
          -5.8353e-01, -6.1312e-01,  6.6431e-01, -1.1991e-02,  3.9430e-01,
          -7.7222e-01, -4.4673e-01, -1.1034e-02,  5.9963e-01, -2.6545e-02,
          -3.3923e-01,  1.0168e-01,  3.6542e-01,  6.9680e-01, -5.7745e-01,
           2.6047e-01,  8.8678e-01, -7.2684e-01,  2.9774e-01, -2.2862e-01,
          -2.6925e-01, -6.0415e-01, -4.8735e-01,  6.8570e-01,  1.2674e-01,
          -3.7454e-01,  3.8836e-01, -1.4712e-01, -2.5363e-01,  2.4132e-01,
          -3.1939e-01,  6.6635e-01,  8.1498e-01, -1.9068e-01, -4.7592e-01,
           1.4402e-01,  6.9687e-01,  6.9328e-01, -5.6145e-01,  6.1426e-01,
          -1.4520e-01,  3.2515e-01,  2.2321e-01, -6.8992e-01]],
        grad_fn=<SqueezeBackward1>),
 tensor([[ 0.1682, -0.5761, -0.6563, -0.1599,  0.8399,  0.2981,  0.6971, -0.5282,
           0.3901,  0.3342, -0.1468,  0.3395,  0.7468, -0.5404, -0.5091,  0.6819,
           0.0952, -0.5432,  0.2348,  0.8992, -0.5835, -0.6131,  0.6643, -0.0120,
           0.3943, -0.7722, -0.4467, -0.0110,  0.5996, -0.0265, -0.3392,  0.1017,
           0.3654,  0.6968, -0.5774,  0.2605,  0.8868, -0.7268,  0.2977, -0.2286,
          -0.2692, -0.6042, -0.4874,  0.6857,  0.1267, -0.3745,  0.3884, -0.1471,
          -0.2536,  0.2413, -0.3194,  0.6663,  0.8150, -0.1907, -0.4759,  0.1440,
           0.6969,  0.6933, -0.5615,  0.6143, -0.1452,  0.3252,  0.2232, -0.6899]],
        grad_fn=<SqueezeBackward1>))

In [ ]:
b, h = y(a)

In [ ]:
z = nn.Linear(64,324)

In [ ]:
z(b)

tensor([[ 0.4596, -0.0354, -0.1195,  ...,  0.1003,  0.3644, -0.2674],
        [-0.1100,  0.1216,  0.0841,  ...,  0.2289, -0.0068,  0.1316],
        [ 0.0357,  0.4911, -0.1851,  ...,  0.3293,  0.4753, -0.2160],
        [-0.0027,  0.0824, -0.1033,  ...,  0.1162,  0.0304,  0.0385],
        [ 0.0006,  0.2563,  0.2202,  ...,  0.2112,  0.3352,  0.0442],
        [ 0.2180, -0.1296,  0.1594,  ...,  0.5474, -0.0401,  0.4520]],
       grad_fn=<AddmmBackward0>)

In [ ]:
class SimpleNN(nn.Module):
  def __init__(self, vocab_size):
    super().__init__()
    self.embedding = nn.Embedding(vocab_size, embedding_dim=50)
    self.rnn = nn.RNN(50, 64)
    self.fc = nn.Linear(64, vocab_size)
    self.sigmoid = nn.Sigmoid()

  def forward(self, question):
    embedded = self.embedding(question)
    output, hidden = self.rnn(embedded)
    output = self.fc(output)
    # The forward pass logic would go here, taking an input 'x'
    return output

In [ ]:
learning_rate = 0.001
epochs = 20

In [ ]:
class SimpleRNN(nn.Module):
    def __init__(self, vocab_size, embedding_dim=50, hidden_size=100):
        super().__init__()
        self.embedding = nn.Embedding(vocab_size, embedding_dim)
        self.rnn = nn.LSTM(embedding_dim, hidden_size, batch_first=True) # Changed to LSTM
        self.fc = nn.Linear(hidden_size, vocab_size)

    def forward(self, x):
        x = self.embedding(x.long())
        out, (h, c) = self.rnn(x) # LSTM returns (output, (h_n, c_n))
        out = self.fc(h.squeeze(0))
        return out

In [ ]:
x = nn.Embedding(324, embedding_dim=50)
y = nn.RNN (50,64, batch_first=True)
z = nn.Linear(64,324)

a = dataset[0][0].unsqueeze(0).long() # Corrected: used .unsqueeze(0) to add batch dimension and .long() for embedding input
print('shape of a:',a.shape)
b = x(a)
print('shape of b:',b.shape)
c, h = y(b)
print('shape of c:',c.shape)
d = z(c.squeeze(0)) # Corrected: typo 'squeze' to 'squeeze' and assignment to method call
print('shape of d:',d.shape)

shape of a: torch.Size([1, 6])
shape of b: torch.Size([1, 6, 50])
shape of c: torch.Size([1, 6, 64])
shape of d: torch.Size([6, 324])

In [ ]:
model = SimpleRNN(len(vocab))

In [ ]:
criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(model.parameters(), learning_rate)

In [ ]:
for epoch in range(epochs):
    total_loss = 0

    for question, answer in dataloader:
        optimizer.zero_grad()

        output = model(question)  # model returns (batch_size, 1, vocab_size)
        loss = criterion(output, answer.squeeze(0))  # output is (1, vocab_size), answer.squeeze(0) is (1,)

        loss.backward()

        optimizer.step()

        total_loss = total_loss + loss.item()

    print(f"Epoch: {epoch+1}, Loss: {total_loss/len(dataloader):.4f}")

Epoch: 1, Loss: 5.7816
Epoch: 2, Loss: 5.1173
Epoch: 3, Loss: 4.1469
Epoch: 4, Loss: 3.2231
Epoch: 5, Loss: 2.3470
Epoch: 6, Loss: 1.6110
Epoch: 7, Loss: 1.0288
Epoch: 8, Loss: 0.6724
Epoch: 9, Loss: 0.4449
Epoch: 10, Loss: 0.3156
Epoch: 11, Loss: 0.2315
Epoch: 12, Loss: 0.1748
Epoch: 13, Loss: 0.1380
Epoch: 14, Loss: 0.1129
Epoch: 15, Loss: 0.0935
Epoch: 16, Loss: 0.0795
Epoch: 17, Loss: 0.0681
Epoch: 18, Loss: 0.0591
Epoch: 19, Loss: 0.0520
Epoch: 20, Loss: 0.0460

In [ ]:
def predict(model, question, threshold=0.5):
    numerical_question = text_to_indices(question, vocab)
    question_tensor = torch.tensor(numerical_question).unsqueeze(0)  # fixed variable name
    output = model(question_tensor)  # fixed: was passing 'question' instead of 'question_tensor'

    probabilities = torch.nn.functional.softmax(output, dim=1)
    value, index = torch.max(probabilities, dim=1)
    print(numerical_question)

    if value < threshold:
        print("I don't know")
    else:
        print(list(vocab.keys())[index])

In [ ]:
#Just tessting how accurate the model predicts
predict(model,"what is the largest planet in our solar system?")

[1, 2, 3, 17, 18, 19, 20, 21, 22]
jupiter

In [ ]:
#observation
list(vocab.keys())[7]

'paris'

In [ ]:
from torch.nn.utils.rnn import pad_sequence

# collate function
def collate_fn(batch):
    questions, answers = zip(*batch)
    questions = pad_sequence(questions, batch_first=True, padding_value=0)
    answers = torch.stack(answers)
    return questions, answers

# split dataset
train_size = int(0.8 * len(dataset))
test_size = len(dataset) - train_size
train_data, test_data = torch.utils.data.random_split(dataset, [train_size, test_size])

# dataloaders with collate_fn
train_loader = DataLoader(train_data, batch_size=32, shuffle=True, collate_fn=collate_fn)
test_loader = DataLoader(test_data, batch_size=32, collate_fn=collate_fn)

In [ ]:

from torch.nn.utils.rnn import pad_sequence

def collate_fn(batch):
    questions, answers = zip(*batch)
    questions = pad_sequence(questions, batch_first=True, padding_value=0)
    answers = torch.stack(answers)
    return questions, answers

train_size = int(0.8 * len(dataset))
test_size = len(dataset) - train_size
train_data, test_data = torch.utils.data.random_split(dataset, [train_size, test_size])

train_loader = DataLoader(train_data, batch_size=32, shuffle=True, collate_fn=collate_fn)
test_loader = DataLoader(test_data, batch_size=32, collate_fn=collate_fn)

# verify
print(train_loader.collate_fn)  # should NOT say default_collate

<function collate_fn at 0x7d05810c6f20>

In [ ]:
from torch.nn.utils.rnn import pad_sequence

def collate_fn(batch):
    questions, answers = zip(*batch)
    questions = pad_sequence(questions, batch_first=True, padding_value=0)
    answers = torch.stack(answers)
    return questions, answers

train_size = int(0.8 * len(dataset))
test_size = len(dataset) - train_size
train_data, test_data = torch.utils.data.random_split(dataset, [train_size, test_size])

train_loader = DataLoader(train_data, batch_size=32, shuffle=True, collate_fn=collate_fn)
test_loader = DataLoader(test_data, batch_size=32, collate_fn=collate_fn)

for epoch in range(epochs):
    model.train()
    total_loss = 0
    correct = 0
    total = 0

    for question, answer in train_loader:
        optimizer.zero_grad()
        output = model(question)
        loss = criterion(output, answer.squeeze(1))
        loss.backward()
        optimizer.step()

        total_loss += loss.item()
        probabilities = torch.nn.functional.softmax(output, dim=1)
        _, predicted = torch.max(probabilities, dim=1)
        correct += (predicted == answer.squeeze()).sum().item()
        total += answer.size(0)

    train_accuracy = correct / total * 100

    model.eval()
    correct = 0
    total = 0

    with torch.no_grad():
        for question, answer in test_loader:
            output = model(question)
            probabilities = torch.nn.functional.softmax(output, dim=1)
            _, predicted = torch.max(probabilities, dim=1)
            correct += (predicted == answer.squeeze()).sum().item()
            total += answer.size(0)

    test_accuracy = correct / total * 100
    print(f"Epoch {epoch+1}/{epochs} | Loss: {total_loss/len(train_loader):.4f} | Train Acc: {train_accuracy:.2f}% | Test Acc: {test_accuracy:.2f}%")

Epoch 1/20 | Loss: 2.0082 | Train Acc: 58.33% | Test Acc: 83.33%
Epoch 2/20 | Loss: 1.2926 | Train Acc: 65.28% | Test Acc: 83.33%
Epoch 3/20 | Loss: 0.9066 | Train Acc: 84.72% | Test Acc: 83.33%
Epoch 4/20 | Loss: 0.7119 | Train Acc: 91.67% | Test Acc: 83.33%
Epoch 5/20 | Loss: 0.5572 | Train Acc: 95.83% | Test Acc: 88.89%
Epoch 6/20 | Loss: 0.5056 | Train Acc: 95.83% | Test Acc: 94.44%
Epoch 7/20 | Loss: 0.4376 | Train Acc: 97.22% | Test Acc: 94.44%
Epoch 8/20 | Loss: 0.3918 | Train Acc: 97.22% | Test Acc: 94.44%
Epoch 9/20 | Loss: 0.2597 | Train Acc: 98.61% | Test Acc: 100.00%
Epoch 10/20 | Loss: 0.2334 | Train Acc: 98.61% | Test Acc: 100.00%
Epoch 11/20 | Loss: 0.2192 | Train Acc: 100.00% | Test Acc: 100.00%
Epoch 12/20 | Loss: 0.1722 | Train Acc: 100.00% | Test Acc: 100.00%
Epoch 13/20 | Loss: 0.1541 | Train Acc: 100.00% | Test Acc: 100.00%
Epoch 14/20 | Loss: 0.1322 | Train Acc: 100.00% | Test Acc: 100.00%
Epoch 15/20 | Loss: 0.1128 | Train Acc: 100.00% | Test Acc: 100.00%
Epoch 16/20 | Loss: 0.1115 | Train Acc: 100.00% | Test Acc: 100.00%
Epoch 17/20 | Loss: 0.1079 | Train Acc: 100.00% | Test Acc: 100.00%
Epoch 18/20 | Loss: 0.0923 | Train Acc: 100.00% | Test Acc: 100.00%
Epoch 19/20 | Loss: 0.0925 | Train Acc: 100.00% | Test Acc: 94.44%
Epoch 20/20 | Loss: 0.0820 | Train Acc: 100.00% | Test Acc: 94.44%